sites:
  gsn:
    templates:
      main_page:
        breadcrumbs:
          required: true
          configurable: true
        navigation:
          required: true
          configurable: true
        site_name:
          required: true
          configurable: true
        content:
          required: true
          configurable: true
        subnavigation_first:
          required: true
          configurable: true
        subnavigation_second:
          required: true
          configurable: true
        subnavigation_third:
          required: true
          configurable: true
        subnavigation_fourth:
          required: true
          configurable: true
        contacts:
          required: true
          configurable: true
        footer:
          required: true
          configurable: true

      inner_page:
        breadcrumbs:
          required: true
          configurable: false
        navigation:
          required: true
          configurable: false
        site_name:
          required: true
          configurable: false
        content:
          required: true
          configurable: true
        subnavigation_first:
          required: true
          configurable: false
        subnavigation_second:
          required: true
          configurable: false
        subnavigation_third:
          required: true
          configurable: false
        subnavigation_fourth:
          required: true
          configurable: false
        contacts:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false
  tgr:
    templates:
      main_page:
        site_name:
          required: true
          configurable: true
        content:
          required: true
          configurable: true
        main_navigation:
          required: true
          configurable: true
        main_bottom_navigation:
          required: true
          configurable: true
        banners:
          required: true
          configurable: true
        secondary_navigation:
          required: true
          configurable: true
        footer:
          required: true
          configurable: true
      inner_page:
        site_name:
          required: true
          configurable: false
        content:
          required: true
          configurable: true
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        banners:
          required: false
          configurable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false
