sites:
  gsn:
    templates:
      main_page:
        breadcrumbs:
          required: true
          configurable: true
        navigation:
          required: true
          configurable: true
        site_name:
          required: true
          configurable: true
        content:
          required: true
          configurable: true
        subnavigation_first:
          required: true
          configurable: true
        subnavigation_second:
          required: true
          configurable: true
        subnavigation_third:
          required: true
          configurable: true
        subnavigation_fourth:
          required: true
          configurable: true
        contacts:
          required: true
          configurable: true
        footer:
          required: true
          configurable: true

      inner_page:
        breadcrumbs:
          required: true
          configurable: false
        navigation:
          required: true
          configurable: false
        site_name:
          required: true
          configurable: false
        content:
          required: true
          configurable: true
        subnavigation_first:
          required: true
          configurable: false
        subnavigation_second:
          required: true
          configurable: false
        subnavigation_third:
          required: true
          configurable: false
        subnavigation_fourth:
          required: true
          configurable: false
        contacts:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

  tgr:
    part_templates:
      blue_pages_item_part: department_chief
      blue_pages_part: list_organizations
      gallery_part: files_list

    templates:
      main_page:
        site_name:
          required: true
          configurable: true
        breadcrumbs:
          required: true
          configurable: true
        content:
          required: true
          configurable: true
        gallery:
          required: false
          configurable: true
        main_navigation:
          required: true
          configurable: true
        main_bottom_navigation:
          required: true
          configurable: true
        map_region:
          required: true
          configurable: true
        banners:
          required: true
          configurable: true
        secondary_navigation:
          required: true
          configurable: true
        footer:
          required: true
          configurable: true

      inner_page:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
        content_second:
          required: false
          configurable: true
        content_third:
          required: false
          configurable: true
        right_side_navigation:
          required: false
          configurable: true
        right_side_facts:
          required: false
          configurable: true
        right_side_links:
          required: false
          configurable: true
        right_side_charts:
          required: false
          configurable: true
        reports:
          required: false
          configurable: true
        gallery:
          required: false
          configurable: true
        banners:
          required: false
          configurable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      organization_structure:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
        content_second:
          required: false
          configurable: true
        banners:
          required: false
          configurable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      department_page:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
        regulation:
          required: false
          configurable: true
        reports:
          required: false
          configurable: true
        dependent_subdivisions:
          required: false
          configurable: true
        links:
          required: false
          configurable: true
        secondary_navigation:
          required: true
          configurable: false
        banners:
          required: false
          configurable: true
        footer:
          required: true
          configurable: false

  kress:
    templates:
      main_page:
        site_name:
          required: true
          configurable: true
      inner_page:
        site_name:
          required: true
          configurable: false

  inotomsk:
    part_templates:
      news_list_part: interview_list_part|belief_list_part|event_list_part
      news_item_part: interview_item_part|belief_item_part|event_item_part

    templates:
      main_page:
        site_name:
          required: true
          configurable: true
        targets:
          required: true
          configurable: true
        main_top_navigation:
          required: true
          configurable: true
        main_bottom_navigation:
          required: true
          configurable: true
        news_list:
          required: true
          configurable: true
        interview_list:
          required: true
          configurable: true
        belief_list:
          required: true
          configurable: true
        last_video:
          required: true
          configurable: true
        event_list:
          required: true
          configurable: true

      inner_page:
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: false
          configurable: true
        navigation_top:
          required: false
          configurable: true
        navigation_right:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true

      event_page:
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: false
          configurable: true
        navigation_top:
          required: false
          configurable: true
        navigation_right:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
        content_second:
          required: false
          configurable: true
        content_third:
          required: false
          configurable: true
