sites:
  tgr: &typical_site
    part_templates:
      news_list_part: main_news_list_part
      announcements_list_part: news_list_part
      blue_pages_item_part: department_chief
      blue_pages_part: list_organizations
      gallery_part: files_list

    templates:
      main_page:
        site_name:
          required: true
          configurable: true
        breadcrumbs:
          required: true
          configurable: true
        actual:
          required: true
          configurable: true
          indexable: true
        calendar_current:
          required: true
          configurable: true
          indexable: true
        calendar_nearest:
          required: true
          configurable: true
          indexable: true
        calendar_gone:
          required: true
          configurable: true
          indexable: true
        governor_message:
          required: true
          configurable: true
          indexable: true
        governor_comments:
          required: true
          configurable: true
          indexable: true
        news:
          required: true
          configurable: true
          indexable: true
        gallery:
          required: false
          configurable: true
          indexable: true
        main_navigation:
          required: true
          configurable: true
        main_bottom_navigation:
          required: true
          configurable: true
        map_region:
          required: true
          configurable: true
          indexable: true
        banners:
          required: true
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: true
        footer:
          required: true
          configurable: true

      inner_page: &tgr_inner_page
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
          indexable: true
        content_second:
          required: false
          configurable: true
          indexable: true
        content_third:
          required: false
          configurable: true
          indexable: true
        right_side_navigation:
          required: false
          configurable: true
        right_side_facts:
          required: false
          configurable: true
          indexable: true
        right_side_links:
          required: false
          configurable: true
          indexable: true
        right_side_charts:
          required: false
          configurable: true
        reports:
          required: false
          configurable: true
          indexable: true
        gallery:
          required: false
          configurable: true
          indexable: true
        banners:
          required: false
          configurable: true
          indexable: true
        main_subnavigation:
          required: true
          configurable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      inner_page_with_social:
        <<: *tgr_inner_page

      entries_list_template:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: true
          configurable: true
          indexable: true
        content_second:
          required: true
          configurable: true
          indexable: true
        content_third:
          required: true
          configurable: true
          indexable: true
        right_side_navigation:
          required: false
          configurable: true
        banners:
          required: false
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      event_show_template:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
          indexable: true
        content_second:
          required: false
          configurable: true
          indexable: true
        content_third:
          required: false
          configurable: true
          indexable: true
        right_side_navigation:
          required: false
          configurable: true
        right_side_facts:
          required: false
          configurable: true
          indexable: true
        right_side_links:
          required: false
          configurable: true
          indexable: true
        right_side_charts:
          required: false
          configurable: true
        reports:
          required: false
          configurable: true
          indexable: true
        gallery:
          required: false
          configurable: true
          indexable: true
        banners:
          required: false
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      organization_structure:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        description:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true
        content_second:
          required: false
          configurable: true
          indexable: true
        banners:
          required: false
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      department_page:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
          indexable: true
        regulation:
          required: false
          configurable: true
          indexable: true
        reports:
          required: false
          configurable: true
          indexable: true
        dependent_subdivisions:
          required: false
          configurable: true
          indexable: true
        links:
          required: false
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        banners:
          required: false
          configurable: true
          indexable: true
        main_subnavigation:
          required: true
          configurable: true
        footer:
          required: true
          configurable: false

      sitemap:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

      fire_situation:
        site_name:
          required: true
          configurable: false
        main_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: true
          configurable: false
        content_first:
          required: false
          configurable: true
          indexable: true
        fire_comments:
          required: true
          configurable: true
          indexable: true
        fire_news:
          required: true
          configurable: true
          indexable: true
        fire_smi_publication:
          required: true
          configurable: true
          indexable: true
        secondary_navigation:
          required: true
          configurable: false
        footer:
          required: true
          configurable: false

  uvto:
    <<: *typical_site

  inotomsk:
    part_templates:
      events_list_part: main_event_list_part
      news_list_part: interview_list_part|belief_list_part|photo_album_list_part
      news_item_part: interview_item_part|belief_item_part|event_item_part|photo_album_item_part

    templates:
      main_page:
        site_name:
          required: true
          configurable: true
        targets:
          required: true
          configurable: true
        main_top_navigation:
          required: true
          configurable: true
        main_bottom_navigation:
          required: true
          configurable: true
        news_list:
          required: true
          configurable: true
          indexable: true
        interview_list:
          required: true
          configurable: true
          indexable: true
        belief_list:
          required: true
          configurable: true
          indexable: true
        last_video:
          required: true
          configurable: true
        last_photo:
          required: true
          configurable: true
        event_list:
          required: true
          configurable: true
          indexable: true

      inner_page: &inotomsk_inner_page
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: false
          configurable: true
        content_header_navigation:
          required: false
          configurable: true
        content_navigation:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true

      event_page:
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: false
          configurable: true
        content_navigation:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true
        content_second:
          required: false
          configurable: true
          indexable: true
        content_third:
          required: false
          configurable: true
          indexable: true

      about_project_page:
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        content_navigation:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true

      barley_break_page: &inotomsk_barley_break_page
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        breadcrumbs:
          required: false
          configurable: true
        content_navigation:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true

      barley_break_inner_page:
        <<: *inotomsk_barley_break_page

      innovation_for_people_page:
        site_name:
          required: true
          configurable: false
        targets:
          required: true
          configurable: false
        main_top_navigation:
          required: true
          configurable: false
        main_bottom_navigation:
          required: true
          configurable: false
        content_navigation:
          required: true
          configurable: true
        content_first:
          required: false
          configurable: true
          indexable: true

      search_results_page:
        <<: *inotomsk_inner_page
