sites:
  tomsk_gov_ru:
    templates:
      main_page:
        navigation:
          type: navigation
          required: true
          configurable: true
        site_name:
          type: text
          required: true
          configurable: true
        content:
          type: html
          required: true
          configurable: true
        footer:
          type: html
          required: true
          configurable: true
      inner_page:
        navigation:
          type: navigation
          required: true
          configurable: false
        site_name:
          type: text
          required: true
          configurable: false
        content:
          type: html
          required: true
          configurable: true
        footer:
          type: html
          required: true
          configurable: false
