#!/usr/bin/env ruby

APP_ROOT = File.expand_path("../..", __FILE__)

require 'optparse'

options = {
  :multiple   => false,
  :dir_mode   => :normal,
  :dir        => "#{APP_ROOT}/tmp/pids",
  :log_dir    => "#{APP_ROOT}/log",
  :backtrace  => true
}

OptionParser.new do |parser|
  parser.on('-n', '--name NAME', "Daemon name") do |name|
    options[:name] = name
  end
  parser.parse!
end

raise OptionParser::MissingArgument unless options[:name]

ENV['BUNDLE_GEMFILE'] ||= "#{APP_ROOT}/Gemfile"

require 'bundler/setup'
require 'daemons'

Daemons.run_proc(options[:name], options) do
  Dir.chdir APP_ROOT
  require "#{APP_ROOT}/config/environment"
  Subscriber.new.start
end

